### ISSUE TITLE
EOP-associated routines inputs

### ISSUE THREAD

**Issue by andreapasquale94** [JuliaSpaceMissionDesign/IERSConventions.jl#3]
https://github.com/JuliaSpaceMissionDesign/IERS.jl/blob/fd2ff8a84246f61cd65fbeaee00633128dfcc470/src/eop.jl#L8

All the EOP-associated interfaces seem to require TT centuries. 
I would switch to days as it is a more standard input and the EOP data are tabulated daily.

I think would be good to use, for example, `tts`, `ttd` and  `ttc` to denote the different inputs within the package, to avoid confusion. Those would be retrieved also in the REPL when writing the function call, thus saving the time to check the documentation for the generic `t` details.

**Comment by MicheleCeresoli** [comment]
Those functions are meant only for internal-use so whether or not the input is standard doesn't really change much. It's just a question of whether the transformation from century\seconds to day is to be performed within the EOP retrieval functions or within the ones that compute the rotations. 

For the input re-naming, I'm not a fan of the notation (for a generic user it might still make no sense what those name mean, at least at the beginning) but I'm ok with it.

**Comment by andreapasquale94** [comment]
> Those functions are meant only for internal-use so whether or not the input is standard doesn't really change much. It's just a question of whether the transformation from century\seconds to day is to be performed within the EOP retrieval functions or within the ones that compute the rotations.

Yes I agree. I think the safest is that we choose a "unit" and be consistent. I would rather use seconds probably, as it is also the `Tempo` unit and we would avoid this kind of operation:

https://github.com/JuliaSpaceMissionDesign/IERS.jl/blob/fd2ff8a84246f61cd65fbeaee00633128dfcc470/src/sidereal.jl#L122

**Comment by MicheleCeresoli** [comment]
I changed all time inputs according to this nomenclature timescale_unit, so TT centuries = `tt_c`, TT seconds = `tt_s`, UT1 days = `ut1_d`. 

EOP are now directly interpolated with TT centuries, so that you don't have to perform the conversion. Additionally, it allows to work with smaller numbers on the interpolators side (which might reduce some rounding\numerical errors).

The operation that you point-out is performed only when computing GMST with the 1996 models, which should be a niche usage so I think it really has a negligible impact.
